name: Deploy Worker

on:
  push:
    paths:
      - 'worker/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler@4

      - name: Deploy Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd worker
          wrangler deploy --api-token "${{ secrets.CF_API_TOKEN }}" --account-id "${{ secrets.CF_ACCOUNT_ID }}"
